### ISSUE TITLE
How to use Hide Commands

### ISSUE THREAD

**Issue by AStupidBear** [m-hall/clean-context-menu#2]
I want to add "Go to declaration" to "Hide Commands", but I don't the correct format. Can you give me an example? Thanks.

**Comment by m-hall** [comment]
You're probably looking for "symbols-view:go-to-declaration".
Items in the list should be comma separated.

To get a list of commands that you can hide:
1) Open the Inspector
2) Open the console tab in the inspector
3) Run the global command "Clean Context Menu: Log Untouched Commands"

This will show all of the commands that you can hide.

**Comment by AStupidBear** [comment]
Thanks!

**Comment by danielhickman** [comment]
Huh, it's supposed to show at `Menu Bar > Packages > Clean Context Menu > Log Untouched Commands`? I don't see it there but I see the code to do just that and I ran that instead.

Edit: I think I ran this last time, and found it in my console history when needing to do it again and forgot where I found it.
```js
var $atom = require('atom');
function listAll() {
        var menus,
            menu,
            i,
            item,
            items;
        // remove menus from the menu bar
        console.log('listAll');
        menus = atom.contextMenu.itemSets;
        for (menu in menus) {
            items = menus[menu].items;
            for (i = items.length; i--;) {
                item = items[i];
                if (!item || !item.command) {
                    continue;
                }
                console.log(item.command);
            }
        }
    }
listAll()
```
